### ISSUE TITLE
An underscore in search crashes the app

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/SdkSearch#13]
```
java.lang.IndexOutOfBoundsException: setSpan (-1 ... 0) starts before 0
    at android.text.SpannableStringInternal.checkRange(SpannableStringInternal.java:442)
    at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:163)
    at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:152)
    at android.text.SpannableString.setSpan(SpannableString.java:46)
    at com.jakewharton.sdksearch.ui.ItemViewHolder.render(ItemViewHolder.kt:97)
    at com.jakewharton.sdksearch.ui.ItemViewHolder.setItem(ItemViewHolder.kt:84)
    at com.jakewharton.sdksearch.ui.ItemAdapter.onBindViewHolder(ItemAdapter.kt:25)
    at com.jakewharton.sdksearch.ui.ItemAdapter.onBindViewHolder(ItemAdapter.kt:30)
    at com.jakewharton.sdksearch.ui.ItemAdapter.onBindViewHolder(ItemAdapter.kt:9)
```

**Comment by SimonMarquis** [comment]
Same crash with `%`.
I'm investigating on this issue right now.

**Comment by JakeWharton** [comment]
From https://sqlite.org/lang_expr.html#like:

> If the optional ESCAPE clause is present, then the expression following the ESCAPE keyword must evaluate to a string consisting of a single character. This character may be used in the LIKE pattern to include literal percent or underscore characters. The escape character followed by a percent symbol (%), underscore (_), or a second instance of the escape character itself matches a literal percent symbol, underscore, or a single escape character, respectively.

So the correct way to solve this is adding an escape character and then escaping `%`, `_`, and the escape character itself onto the query.

**Comment by JakeWharton** [comment]
Fix is in alpha channel.
