### ISSUE TITLE
1.3.0 is broken, le sigh

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/SdkSearch#96]
```
java.lang.IllegalArgumentException: Unable to create converter for java.util.Map<java.lang.String, java.util.List<com.jakewharton.sdksearch.api.dac.Item>>
    for method DocumentationService.list
        at retrofit2.ServiceMethod$Builder.methodError(unknown:755)
        at retrofit2.ServiceMethod$Builder.createResponseConverter(unknown:741)
        at retrofit2.ServiceMethod$Builder.build(unknown:172)
        at retrofit2.Retrofit.loadServiceMethod(unknown:170)
        at retrofit2.Retrofit$1.invoke(unknown:147)
        at java.lang.reflect.Proxy.invoke(Proxy.java:913)
        at $Proxy0.list(Unknown:-1)
        at com.jakewharton.sdksearch.sync.ItemSynchronizer.load(unknown:50)
        at com.jakewharton.sdksearch.sync.ItemSynchronizer$loader$1$doResume$$inlined$consumeEach$lambda$1.doResume(unknown:32)
        at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(unknown:54)
        at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(unknown:161)
        at kotlinx.coroutines.experimental.DispatchedContinuation.run(unknown:25)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1152)
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1990)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1938)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: kotlinx.serialization.SerializationException: Can't locate default serializer for class class com.jakewharton.sdksearch.api.dac.Item (Kotlin reflection is not available)
        at kotlinx.serialization.SerializationKt.serializer(unknown:23)
        at kotlinx.serialization.internal.SerialCache.lookupSerializer$kotlinx_serialization_runtime(unknown:80)
        at kotlinx.serialization.ResolvingKt.serializerByClass(unknown:56)
        at kotlinx.serialization.ResolvingKt.serializerByClass$default(unknown:56)
        at kotlinx.serialization.ResolvingKt.serializerByTypeToken(unknown:62)
        at kotlinx.serialization.ResolvingKt.serializerByTypeToken(unknown:72)
        at kotlinx.serialization.ResolvingKt.serializerByTypeToken(unknown:74)
        at com.jakewharton.retrofit2.converter.kotlinx.serialization.Factory.responseBodyConverter(unknown:26)
        at retrofit2.Retrofit.nextResponseBodyConverter(unknown:330)
        at retrofit2.Retrofit.responseBodyConverter(unknown:313)
        at retrofit2.ServiceMethod$Builder.createResponseConverter(unknown:739)
        at retrofit2.ServiceMethod$Builder.build(unknown:172)
        at retrofit2.Retrofit.loadServiceMethod(unknown:170)
        at retrofit2.Retrofit$1.invoke(unknown:147)
        at java.lang.reflect.Proxy.invoke(Proxy.java:913)
        at $Proxy0.list(Unknown:-1)
        at com.jakewharton.sdksearch.sync.ItemSynchronizer.load(unknown:50)
        at com.jakewharton.sdksearch.sync.ItemSynchronizer$loader$1$doResume$$inlined$consumeEach$lambda$1.doResume(unknown:32)
        at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(unknown:54)
        at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(unknown:161)
        at kotlinx.coroutines.experimental.DispatchedContinuation.run(unknown:25)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1152)
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1990)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1938)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
probably R8's fault

**Comment by JakeWharton** [comment]
Fixed by 5fdb9c2c97ffa5adb754f16c018692b613fd5ff8
